server:
  port: 8011
  servlet:
    context-path: /

spring:
  # IDENTITY ===============================================================================
  application:
    name: customer-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

auth_token: aW5mdXNpb25zb2Z0OnBhc3N3b3Jk

management:
  endpoint:
    health:
      enabled: true
      roles: ["ADMIN", "USER"]
      show-details: when_authorized
    httptrace:
      enabled: true
  endpoints:
    web:
      base-path: /application
      exposure:
        include: "*"
        exclude: loggers

info:
  app:
    name: Customer Service
    java:
      version: 8
    type: Spring Boot

# LOGGING ================================================================================
logging:
  pattern:
    console:  "%d{yyyy-MM-dd HH:mm:ss} %-5level [%15.15thread] [%-35.35logger{35}] : %msg%n"
  level:
    root: INFO
    com.practice.mcs1: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.cloud.netflix.zuul: WARN