server:
  port: 8761
  servlet:
    context-path: /

spring:
  # IDENTITY ===============================================================================
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true